language: node_js
node_js:
  - "12"
services:
  - docker
before_install:
  - yarn
script:
  - yarn build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t xdzyk/websocket:latest
  - docker push xdzyk/websocket:latest